# Generated by Django 5.1.5 on 2025-01-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[("W", "Win"), ("L", "Lose"), ("I", "InProgress")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_moved_at", models.DateTimeField(auto_now_add=True)),
                ("board", models.TextField(null=False)),
                ("bomb_count", models.IntegerField()),
                ("rows", models.IntegerField()),
                ("columns", models.IntegerField()),
                ("moves", models.TextField(null=False)),
            ],
        ),
    ]
